// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: customtransfer/packet.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CustomtransferPacketData struct {
	// Types that are valid to be assigned to Packet:
	//	*CustomtransferPacketData_NoData
	//	*CustomtransferPacketData_OrderPacket
	Packet isCustomtransferPacketData_Packet `protobuf_oneof:"packet"`
}

func (m *CustomtransferPacketData) Reset()         { *m = CustomtransferPacketData{} }
func (m *CustomtransferPacketData) String() string { return proto.CompactTextString(m) }
func (*CustomtransferPacketData) ProtoMessage()    {}
func (*CustomtransferPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_664d0959b502b5c4, []int{0}
}
func (m *CustomtransferPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustomtransferPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustomtransferPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustomtransferPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomtransferPacketData.Merge(m, src)
}
func (m *CustomtransferPacketData) XXX_Size() int {
	return m.Size()
}
func (m *CustomtransferPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomtransferPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_CustomtransferPacketData proto.InternalMessageInfo

type isCustomtransferPacketData_Packet interface {
	isCustomtransferPacketData_Packet()
	MarshalTo([]byte) (int, error)
	Size() int
}

type CustomtransferPacketData_NoData struct {
	NoData *NoData `protobuf:"bytes,1,opt,name=noData,proto3,oneof" json:"noData,omitempty"`
}
type CustomtransferPacketData_OrderPacket struct {
	OrderPacket *OrderPacketData `protobuf:"bytes,2,opt,name=orderPacket,proto3,oneof" json:"orderPacket,omitempty"`
}

func (*CustomtransferPacketData_NoData) isCustomtransferPacketData_Packet()      {}
func (*CustomtransferPacketData_OrderPacket) isCustomtransferPacketData_Packet() {}

func (m *CustomtransferPacketData) GetPacket() isCustomtransferPacketData_Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (m *CustomtransferPacketData) GetNoData() *NoData {
	if x, ok := m.GetPacket().(*CustomtransferPacketData_NoData); ok {
		return x.NoData
	}
	return nil
}

func (m *CustomtransferPacketData) GetOrderPacket() *OrderPacketData {
	if x, ok := m.GetPacket().(*CustomtransferPacketData_OrderPacket); ok {
		return x.OrderPacket
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CustomtransferPacketData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CustomtransferPacketData_NoData)(nil),
		(*CustomtransferPacketData_OrderPacket)(nil),
	}
}

type NoData struct {
}

func (m *NoData) Reset()         { *m = NoData{} }
func (m *NoData) String() string { return proto.CompactTextString(m) }
func (*NoData) ProtoMessage()    {}
func (*NoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_664d0959b502b5c4, []int{1}
}
func (m *NoData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NoData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoData.Merge(m, src)
}
func (m *NoData) XXX_Size() int {
	return m.Size()
}
func (m *NoData) XXX_DiscardUnknown() {
	xxx_messageInfo_NoData.DiscardUnknown(m)
}

var xxx_messageInfo_NoData proto.InternalMessageInfo

// OrderPacketData defines a struct for the packet payload
type OrderPacketData struct {
	Receiver      string `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Instrument    string `protobuf:"bytes,2,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Amount        string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Denom         string `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`
	Direction     string `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	Price         string `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Threshold     string `protobuf:"bytes,7,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Senderaddress string `protobuf:"bytes,8,opt,name=senderaddress,proto3" json:"senderaddress,omitempty"`
}

func (m *OrderPacketData) Reset()         { *m = OrderPacketData{} }
func (m *OrderPacketData) String() string { return proto.CompactTextString(m) }
func (*OrderPacketData) ProtoMessage()    {}
func (*OrderPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_664d0959b502b5c4, []int{2}
}
func (m *OrderPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OrderPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OrderPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OrderPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderPacketData.Merge(m, src)
}
func (m *OrderPacketData) XXX_Size() int {
	return m.Size()
}
func (m *OrderPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_OrderPacketData proto.InternalMessageInfo

func (m *OrderPacketData) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *OrderPacketData) GetInstrument() string {
	if m != nil {
		return m.Instrument
	}
	return ""
}

func (m *OrderPacketData) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *OrderPacketData) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *OrderPacketData) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *OrderPacketData) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *OrderPacketData) GetThreshold() string {
	if m != nil {
		return m.Threshold
	}
	return ""
}

func (m *OrderPacketData) GetSenderaddress() string {
	if m != nil {
		return m.Senderaddress
	}
	return ""
}

// OrderPacketAck defines a struct for the packet acknowledgment
type OrderPacketAck struct {
}

func (m *OrderPacketAck) Reset()         { *m = OrderPacketAck{} }
func (m *OrderPacketAck) String() string { return proto.CompactTextString(m) }
func (*OrderPacketAck) ProtoMessage()    {}
func (*OrderPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_664d0959b502b5c4, []int{3}
}
func (m *OrderPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OrderPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OrderPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OrderPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderPacketAck.Merge(m, src)
}
func (m *OrderPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *OrderPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_OrderPacketAck proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CustomtransferPacketData)(nil), "hubchain.customtransfer.CustomtransferPacketData")
	proto.RegisterType((*NoData)(nil), "hubchain.customtransfer.NoData")
	proto.RegisterType((*OrderPacketData)(nil), "hubchain.customtransfer.OrderPacketData")
	proto.RegisterType((*OrderPacketAck)(nil), "hubchain.customtransfer.OrderPacketAck")
}

func init() { proto.RegisterFile("customtransfer/packet.proto", fileDescriptor_664d0959b502b5c4) }

var fileDescriptor_664d0959b502b5c4 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xbd, 0x6e, 0xdb, 0x30,
	0x14, 0x85, 0xa5, 0xb6, 0x56, 0x65, 0x1a, 0xfd, 0x01, 0x61, 0xb4, 0x84, 0x5b, 0xd0, 0x85, 0xd0,
	0xc1, 0x93, 0x04, 0xb7, 0x93, 0xc7, 0xba, 0x1d, 0x3a, 0x04, 0x49, 0xe0, 0x31, 0x1b, 0x45, 0xdd,
	0x58, 0x82, 0x23, 0x52, 0x20, 0x29, 0x23, 0x79, 0x8b, 0xbc, 0x48, 0xde, 0x23, 0xa3, 0xc7, 0x8c,
	0x81, 0xfd, 0x08, 0x79, 0x81, 0x40, 0xa4, 0xff, 0x01, 0x6f, 0xf7, 0x1c, 0x9e, 0xef, 0x5e, 0x92,
	0xb8, 0xe8, 0x1b, 0xaf, 0xb5, 0x91, 0xa5, 0x51, 0x4c, 0xe8, 0x6b, 0x50, 0x49, 0xc5, 0xf8, 0x0c,
	0x4c, 0x5c, 0x29, 0x69, 0x24, 0xfe, 0x9a, 0xd7, 0x29, 0xcf, 0x59, 0x21, 0xe2, 0xc3, 0x54, 0x8f,
	0x72, 0xa9, 0x4b, 0xa9, 0x93, 0x94, 0x69, 0x48, 0xe6, 0xc3, 0x14, 0x0c, 0x1b, 0x26, 0x5c, 0x16,
	0xc2, 0x81, 0xbd, 0xee, 0x54, 0x4e, 0xa5, 0x2d, 0x93, 0xa6, 0x72, 0x6e, 0xf4, 0xe0, 0x23, 0xf2,
	0xf7, 0xa0, 0xd1, 0xa5, 0x9d, 0xf6, 0x8f, 0x19, 0x86, 0x47, 0x28, 0x10, 0xb2, 0xa9, 0x88, 0xff,
	0xc3, 0x1f, 0x74, 0x7e, 0xf5, 0xe3, 0x13, 0xc3, 0xe3, 0x73, 0x1b, 0xfb, 0xef, 0x4d, 0xd6, 0x00,
	0x3e, 0x43, 0x1d, 0xa9, 0xb2, 0x4d, 0x37, 0xf2, 0xc6, 0xf2, 0x83, 0x93, 0xfc, 0xc5, 0x2e, 0xbb,
	0x6e, 0xb4, 0x8f, 0x8f, 0x43, 0x14, 0xb8, 0x4f, 0x88, 0x42, 0x14, 0xb8, 0x59, 0xd1, 0x8b, 0x8f,
	0x3e, 0x1d, 0x61, 0xb8, 0x87, 0x42, 0x05, 0x1c, 0x8a, 0x39, 0x28, 0x7b, 0xe5, 0xf6, 0x64, 0xab,
	0x31, 0x45, 0xa8, 0x10, 0xda, 0xa8, 0xba, 0x04, 0xe1, 0x2e, 0xd4, 0x9e, 0xec, 0x39, 0xf8, 0x0b,
	0x0a, 0x58, 0x29, 0x6b, 0x61, 0xc8, 0x5b, 0x7b, 0xb6, 0x56, 0xb8, 0x8b, 0x5a, 0x19, 0x08, 0x59,
	0x92, 0x77, 0xd6, 0x76, 0x02, 0x7f, 0x47, 0xed, 0xac, 0x50, 0xc0, 0x4d, 0x21, 0x05, 0x69, 0xd9,
	0x93, 0x9d, 0xd1, 0x30, 0x95, 0x2a, 0x38, 0x90, 0xc0, 0x31, 0x56, 0x34, 0x8c, 0xc9, 0x15, 0xe8,
	0x5c, 0xde, 0x64, 0xe4, 0xbd, 0x63, 0xb6, 0x06, 0xfe, 0x89, 0x3e, 0x68, 0x10, 0x19, 0x28, 0x96,
	0x65, 0x0a, 0xb4, 0x26, 0xa1, 0x4d, 0x1c, 0x9a, 0xd1, 0x67, 0xf4, 0x71, 0xef, 0xd1, 0x7f, 0xf8,
	0x6c, 0x3c, 0x7a, 0x5c, 0x52, 0x7f, 0xb1, 0xa4, 0xfe, 0xf3, 0x92, 0xfa, 0xf7, 0x2b, 0xea, 0x2d,
	0x56, 0xd4, 0x7b, 0x5a, 0x51, 0xef, 0xaa, 0xbf, 0xf9, 0xed, 0xe4, 0x36, 0x39, 0x5a, 0x29, 0x73,
	0x57, 0x81, 0x4e, 0x03, 0xbb, 0x03, 0xbf, 0x5f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x9a, 0xff,
	0x40, 0x71, 0x02, 0x00, 0x00,
}

func (m *CustomtransferPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustomtransferPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustomtransferPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Packet != nil {
		{
			size := m.Packet.Size()
			i -= size
			if _, err := m.Packet.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *CustomtransferPacketData_NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustomtransferPacketData_NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.NoData != nil {
		{
			size, err := m.NoData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *CustomtransferPacketData_OrderPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustomtransferPacketData_OrderPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.OrderPacket != nil {
		{
			size, err := m.OrderPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *NoData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *OrderPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrderPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OrderPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Senderaddress) > 0 {
		i -= len(m.Senderaddress)
		copy(dAtA[i:], m.Senderaddress)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Senderaddress)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Threshold) > 0 {
		i -= len(m.Threshold)
		copy(dAtA[i:], m.Threshold)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Threshold)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Price) > 0 {
		i -= len(m.Price)
		copy(dAtA[i:], m.Price)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Price)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Direction) > 0 {
		i -= len(m.Direction)
		copy(dAtA[i:], m.Direction)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Direction)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Instrument) > 0 {
		i -= len(m.Instrument)
		copy(dAtA[i:], m.Instrument)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Instrument)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OrderPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrderPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OrderPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CustomtransferPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Packet != nil {
		n += m.Packet.Size()
	}
	return n
}

func (m *CustomtransferPacketData_NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NoData != nil {
		l = m.NoData.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *CustomtransferPacketData_OrderPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OrderPacket != nil {
		l = m.OrderPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *OrderPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Instrument)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Direction)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Threshold)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Senderaddress)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *OrderPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CustomtransferPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustomtransferPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustomtransferPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &NoData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &CustomtransferPacketData_NoData{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &OrderPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &CustomtransferPacketData_OrderPacket{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NoData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NoData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NoData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OrderPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrderPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrderPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Instrument", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Instrument = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Direction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Direction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Threshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Threshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Senderaddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Senderaddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OrderPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrderPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrderPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
