version: '3'
services:
  node0:
    image: gcr.io/devops-project-allqd0/evmos:fi8be-evmos-0.0.1-0
    ports:
      - 26657 # rpc.laddr
      - 9090  # grpc 
      - 26656 # p2p 
      - 9091  # grpc-ws 
      - 1317  # api 
      - 8545  # json-rpc 
      - 8546 # json-rpc-ws 
    networks:
      localnet:
        ipv4_address: 192.167.10.2

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.167.10.0/16